frontend/models/Pemesanan.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "pemesanan".
 *
 * @property int $id_pemesanan
 * @property int $id_rumahindekos
 * @property int $id_customer
 * @property string $tanggal
 * @property string $waktu
 * @property int $jumlah_kamar
 * @property int $status
 *
 * @property RumahIndekos $rumahindekos
 * @property Customer $customer
 * @property StatusPemesanan $status0
 */
class Pemesanan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pemesanan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_rumahindekos', 'id_customer'], 'required'],
            [['id_rumahindekos', 'id_customer', 'jumlah_kamar', ], 'integer'],
            [['tanggal', 'waktu'], 'safe'],
            [['jumlah_kamar'], 'integer', 'min' => 1],
            [['id_rumahindekos'], 'exist', 'skipOnError' => true, 'targetClass' => RumahIndekos::className(), 'targetAttribute' => ['id_rumahindekos' => 'ID_RUMAHINDEKOS']],
            [['id_customer'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['id_customer' => 'ID_CUSTOMER']],
            // [['status_pemesanan'], 'exist', 'skipOnError' => true, 'targetClass' => StatusPemesanan::className(), 'targetAttribute' => ['status_pemesanan' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_pemesanan' => 'Id Pemesanan',
            'nama_rumahindekos' => 'Nama Rumahindekos',
            'id_customer' => 'Id Customer',
            'tanggal' => 'Tanggal',
            'waktu' => 'Waktu',
            'jumlah_kamar' => 'Jumlah Kamar',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRumahindekos()
    {
        return $this->hasOne(RumahIndekos::className(), ['ID_RUMAHINDEKOS' => 'id_rumahindekos']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNamaRumahindekos()
    {
        return $this->hasOne(RumahIndekos::className(), ['NAMA_RUMAHINDEKOS' => 'nama_rumahindekos']);
    }

    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['ID_CUSTOMER' => 'id_customer']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(StatusPemesanan::className(), ['id_status' => 'id_status']);
    }
}

frontend/controllers/PemesananController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Pemesanan;
use frontend\models\Vendor;
use frontend\models\RumahIndekos;
use frontend\models\search\PemesananSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use yii\data\ActiveDataProvider;

/**
 * PemesananController implements the CRUD actions for Pemesanan model.
 */
class PemesananController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {   
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['confirm', 'reject', 'create'],
                'rules' => [
                    [
                        'actions' => ['confirm', 'reject'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserVendor(Yii::$app->user->identity->username);
                        }
                   ],
                   [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserCustomer(Yii::$app->user->identity->username);
                        }
                ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pemesanan models.
     * @return mixed
     */
    public function actionIndex()
    {
        // $user = User::findOne(Yii::$app->user->id);
        // $vendor = Vendor::find()->where(['ID_AKUN' => $user->id])->one();

        // $rumah_indekos = RumahIndekos::find()->where(['ID_VENDOR' => $vendor->ID_VENDOR])->one();

        // $pemesanan = Pemesanan::find()->where(['id_rumahindekos' => $rumah_indekos->ID_RUMAHINDEKOS])->all();;
        $searchModel = new PemesananSearch();
        
        // $dataProvider = new ActiveDataProvider([
        //     'query' => Pemesanan::find()->where(['id_rumahindekos' => $rumah_indekos->ID_RUMAHINDEKOS])->orderBy('id_pemesanan asc'),
        // ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pemesanan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $pemesanan = Pemesanan::findOne($id);

        return $this->render('view', [
            'model' => $pemesanan,
        ]);
    }

    /**
     * Creates a new Pemesanan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pemesanan();

        if ($model->load(Yii::$app->request->post())) {

            $userId = Yii::$app->user->getId();

            $id = (new \yii\db\Query())
                  ->select(['ID_CUSTOMER'])
                  ->from('CUSTOMER')
                  ->where(['ID_AKUN' => $userId])
                  ->all();

            $model->id_customer = $id;
            $model->tanggal = date('Y-m-d');
            $model->waktu = date('H:i:s');
            $model->id_status = 1;

            // echo '<pre />';
            // print_r($model);
            // die;

            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id_pemesanan]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pemesanan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_pemesanan]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pemesanan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pemesanan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pemesanan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pemesanan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionCancel($id){
        $pemesanan = Pemesanan::findOne($id);
        $pemesanan->id_status = 1;
        // var_dump($pemesanan->id_status);
        // die();
        // $pemesanan->status = 1;
        $pemesanan->save();

        return $this->actionIndex();
    }

    public function actionConfirm($id){
        $pemesanan = Pemesanan::findOne($id);
        $pemesanan->id_status = 2;
        // var_dump($pemesanan->id_status);
        // die();
        // $pemesanan->status = 2;
        $pemesanan->save();

        return $this->actionIndex();
    }

    public function actionReject($id){
        $pemesanan = Pemesanan::findOne($id);
        $pemesanan->id_status = 3;
        // echo "<pre/>";
        // var_dump($pemesanan);
        // die();
        // $pemesanan->status = 2;
        $pemesanan->save();

        return $this->actionIndex();
    }
}

frontend/views/pemesanan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datetimepicker\DateTimePicker;
use frontend\models\RumahIndekos;

/* @var $this yii\web\View */
/* @var $model frontend\models\Pemesanan */
/* @var $form yii\widgets\ActiveForm */

$datetime = new DateTime();
$datetime->modify('+2 day');
// $dim = Dim::find()->where('deleted != 1')->andWhere(['user_id' => Yii::$app->user->identity->user_id])->one();

$id = $_GET['id'];
$rumah_indekos = RumahIndekos::findOne($id);

// var_dump($rumah_indekos->STOK);

?>

<div class="pemesanan-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
        $id = $_GET['id'];
    ?>
    <div class="" style="padding-left:30%; padding-right:30%;" >
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $form->field($model, 'id_rumahindekos')->hiddenInput(['value'=> $id])->label(false);?>
        
        <?= $form->field($model, 'tanggal')->widget(DateTimePicker::className(), [
            'language' => 'en',
            'size' => 'ms',
            'pickButtonIcon' => 'glyphicon glyphicon-time',
            'inline' => false,
            'clientOptions' => [
                'pickerPosition' => 'bottom-left',
                'autoclose' => true,
                'format' => 'yyyy-mm-dd', // if inline = false
                // 'todayBtn' => true,
                'startDate' => date($datetime->format("Y-m-d")),
            ]
        ]);?>

    

    <!-- <?= $form->field($model, 'tanggal')->textInput() ?> -->

    <!-- <?= $form->field($model, 'waktu')->textInput() ?>  -->

    <?= $form->field($model, 'jumlah_kamar')->textInput(['type' => 'number', 'max' => $rumah_indekos->STOK]) ?>

    <!-- <?= $form->field($model, 'status')->textInput() ?> -->

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    </div>
    
    <?php ActiveForm::end(); ?>

</div>
 

frontend/views/pemesanan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\PemesananSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pemesanan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_pemesanan') ?>

    <?= $form->field($model, 'id_rumahindekos') ?>

    <?= $form->field($model, 'id_customer') ?>

    <?= $form->field($model, 'tanggal') ?>

    <?= $form->field($model, 'waktu') ?>

    <?php // echo $form->field($model, 'jumlah_kamar') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/pemesanan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Pemesanan */

$this->title = 'Pesan Rumah Indekos';
$this->params['breadcrumbs'][] = ['label' => 'Pemesanan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pemesanan-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/pemesanan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use frontend\models\RumahIndekos;
use frontend\models\StatusPemesanan;
use frontend\models\Customer;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\search\PemesananSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pemesanan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pemesanan-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <!-- <p>
        <!-- <?= Html::a('Create Pemesanan', ['create'], ['class' => 'btn btn-success']) ?> -->
    </p> 

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
        
            // 'id_pemesanan',
            // 'NAMA_RUMAHINDEKOS',
            [
                'attribute' => 'namaKos',
                'label' => 'Nama Rumah Indekos',
                'filter' => ArrayHelper::map(RumahIndekos::find()->all(), 'ID_RUMAHINDEKOS', 'NAMA_RUMAHINDEKOS'),
                'filterInputOptions' => ['class' => 'form-control', 'id' => 'ID_VENDOR', 'prompt' => 'Semua'],
                'value' => 'rumahindekos.NAMA_RUMAHINDEKOS',
            ],

            [
                'attribute' => 'namaCustomer',
                'label' => 'Nama Customer',
                'value' => 'customer.NAMA_CUSTOMER',
            ],
            'tanggal',
            'jumlah_kamar',
            // [
            //     'attribute' => 'no_telp_Customer',
            //     'label' => 'No. Telepon Customer',
            //     'value' => 'customer.NO_TELP_CUSTOMER',
            // ],
            // 'NO_TELP_CUSTOMER',
            [
                'attribute' => 'id_status',
                'label' => 'Status',
                'filter' => ArrayHelper::map(StatusPemesanan::find()->all(), 'id_status', 'status_pemesanan'),
                'filterInputOptions' => ['class' => 'form-control', 'id' => NULL, 'prompt' => 'ALL'],
                'value' => 'status.status_pemesanan',
            ],


            
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {confirm} {reject}',
                'buttons' => [
                    'confirm' => function($url, $model){
                        return Html::a('', ['pemesanan/confirm', 'id' => $model->id_pemesanan], ['class' => 'glyphicon glyphicon-ok']);
                    },
                    'reject' => function($url, $model){
                        return Html::a('', ['pemesanan/reject', 'id' => $model->id_pemesanan], ['class' => 'glyphicon glyphicon-remove']);
                    }
                ],
            ],
        ],
    ]); ?>


</div>

frontend/views/pemesanan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Pemesanan */

$this->title = 'Update Pemesanan: ' . $model->id_pemesanan;
$this->params['breadcrumbs'][] = ['label' => 'Pemesanan', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_pemesanan, 'url' => ['view', 'id' => $model->id_pemesanan]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pemesanan-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/pemesanan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\models\Customer;
use frontend\models\User;
/* @var $this yii\web\View */
/* @var $model frontend\models\Pemesanan */

$session = Yii::$app->session;
$user = User::find()->where(['username' => Yii::$app->user->identity->username])->one();

$this->title = $model->id_pemesanan;
$this->params['breadcrumbs'][] = ['label' => 'Pemesanan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="pemesanan-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_pemesanan',
            'id_rumahindekos',
            'id_customer',
            'tanggal',
            'jumlah_kamar',
            // [
            //     'attribute' => 'no_telp_Customer',
            //     'label' => 'No. Telepon Customer',
            //     'value' => 'customer.NO_TELP_CUSTOMER',
            // ],
           'id_status'
            
        ],
    ]) ?>
 <?php  
if($user['role'] == 20){?>
    <p>
       <?= Html::a('Cancel', ['delete', 'id' => $model->id_pemesanan], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Apakah anda yakin membatalkan pemesanan anda?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php
        }
    ?>

</div>