frontend/models/Ulasan.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "ulasan".
 *
 * @property int $ID_ULASAN
 * @property int $ID_CUSTOMER
 * @property int $ID_RUMAHINDEKOS
 * @property string $KOMENTAR
 * @property int $RATING
 *
 * @property Customer $cUSTOMER
 * @property RumahIndekos $rUMAHINDEKOS
 */
class Ulasan extends \yii\db\ActiveRecord
{
    public $SUMS;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ulasan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['ID_CUSTOMER', 'ID_RUMAHINDEKOS'], 'required'],
            [['ID_CUSTOMER', 'ID_RUMAHINDEKOS', 'RATING'], 'integer'],
            [['KOMENTAR'], 'string', 'max' => 128],
            [['ID_CUSTOMER'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['ID_CUSTOMER' => 'ID_CUSTOMER']],
            [['ID_RUMAHINDEKOS'], 'exist', 'skipOnError' => true, 'targetClass' => RumahIndekos::className(), 'targetAttribute' => ['ID_RUMAHINDEKOS' => 'ID_RUMAHINDEKOS']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'ID_ULASAN' => 'Id Ulasan',
            'ID_CUSTOMER' => 'Id Customer',
            'ID_RUMAHINDEKOS' => 'Id Rumahindekos',
            'KOMENTAR' => 'Komentar',
            'RATING' => 'Rating',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['ID_CUSTOMER' => 'ID_CUSTOMER']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRumahindekos()
    {
        return $this->hasOne(RumahIndekos::className(), ['ID_RUMAHINDEKOS' => 'ID_RUMAHINDEKOS']);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Customer;
use frontend\models\Vendor;
use frontend\models\search\UserSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'about', 'contact'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['about', 'contact'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserVendor(Yii::$app->user->identity->username);
                        }
                   ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    // public function actionLogin()
    // {
    //     if (!Yii::$app->user->isGuest) {
    //         return $this->goHome();
    //     }

    //     $model = new LoginForm();
    //     if ($model->load(Yii::$app->request->post()) && $model->login()) {
    //         return $this->goBack();
    //     } else {
    //         $model->password = '';

    //         return $this->render('login', [
    //             'model' => $model,
    //         ]);
    //     }
    // }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && ($model->loginCustomer() || $model->loginVendor() || $model->loginAdmin())) {
            return $this->goBack();
            }
             else {
            return $this->render('login', [
            'model' => $model,
            ]);     
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        $modelRegister = new Customer();
        if ($model->load(Yii::$app->request->post())) {

            $model->signup("customer");

            $id = User::find()->max('id');

            $data = Yii::$app->request->post()['Customer'];

            $modelRegister->ID_AKUN = $id;
            $modelRegister->NAMA_CUSTOMER = $data['NAMA_CUSTOMER'];
            $modelRegister->ALAMAT_CUSTOMER = $data['ALAMAT_CUSTOMER'];
            $modelRegister->NO_TELEPON_CUSTOMER = $data['NO_TELEPON_CUSTOMER'];
            $modelRegister->JENIS_KELAMIN = $data['JENIS_KELAMIN'];
            $modelRegister->EMAIL_CUSTOMER = $model->email;

            // echo "<pre />";
            // print_r($modelRegister);
            // die;
            $modelRegister->save();            

            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
            'modelRegister' => $modelRegister,
        ]);
    }

    public function actionSignupVendor()
    {
        $model = new SignupForm();
        $modelRegisterVendor = new Vendor();
        if ($model->load(Yii::$app->request->post())) {

            $model->signup("vendor");

            // $id = User::find()->orderBy(['id' => SORT_DESC])->one();
            // echo $id;die();

            // var_dump($model);
            // die();

            $id = User::find()
                                  ->select(['id'])
                                  ->orderBy(['id' => SORT_DESC])
                                  ->limit(1)
                                  ->one();
                                //   echo $id->id;die();

            $data = Yii::$app->request->post()['Vendor'];

            $user = User::find()->where(['username' => $model->username])->one();

            $modelRegisterVendor->ID_AKUN = $user->id;
            $modelRegisterVendor->NAMA_VENDOR = $data['NAMA_VENDOR'];
            $modelRegisterVendor->ALAMAT_VENDOR = $data['ALAMAT_VENDOR'];
            $modelRegisterVendor->NO_TELEPON__VENDOR = $data['NO_TELEPON__VENDOR'];
            $modelRegisterVendor->EMAIL_VENDOR = $model->email;

            // die();

            if($modelRegisterVendor->save()){
                Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
                return $this->goHome();
            }else{
                echo "<pre>";
                var_dump($modelRegisterVendor);
                echo "</pre>";
            }

            
        }

        return $this->render('signupVendor', [
            'model' => $model,
            'modelRegisterVendor' => $modelRegisterVendor,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Kata sandi baru telah disimpan.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Email anda berhasil dikonfirmasi!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Hubungi kami jika kesalahan yang terjadi adalah kesalahan server. Terima kasih.
    </p>

</div>

frontend/views/site/index.php
<?php
use frontend\models\Ulasan;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'TobaKos';
?>
<div class="site-index">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" >
    <div class="item active">
      <img src="image/Logo1.png" alt="Kost Makmur">
      <!-- <div class="carousel-caption">
        <h2>Kost Makmur</h2>
      </div> -->
    </div>
    <div class="item">
      <img src="image/iklan1.png" alt="Kost Jaya">
      <!-- <div class="carousel-caption">
        <h2>Kost Jaya</h2>
      </div> -->
    </div>
    <div class="item">
      <img src="image/Carousel1.png" alt="Kost Ceria">
      <!-- <div class="carousel-caption">
        <h2>Kost Ceria</h2>
      </div> -->
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-center" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<hr/>
<h3><b>REKOMENDASI</b></h3>
    <div class="body-content">
      <div class="row">
        <?php
          $rumahIndekos = Ulasan::find()
                                  ->select(['AVG(RATING) AS SUMS, ID_RUMAHINDEKOS'])
                                  ->groupBy(['ID_RUMAHINDEKOS'])
                                  ->orderBy(['SUMS' => SORT_DESC])
                                  ->limit(3)
                                  ->all();

          foreach ($rumahIndekos as $row){
      ?>
        <div class="col-lg-4">
          <div class= "row">
            <div class= "col-lg-12 offset-md-1">
            <h5 class= "pull-right"> Rating: <?php 
                echo Yii::$app->formatter->asDecimal($row->SUMS,1);
            ?>/5</h5>
            </div>  
          </div>
          <!-- <a href="#"><i class="fa fa-circle text-success"></i> Rating</a> -->
            <a href = "<?= Url::to(['rumah-indekos/view', 'id' => $row->rumahindekos->ID_RUMAHINDEKOS]) ?>" style="color:#000000">
              <img src="image/<?php echo $row->rumahindekos->GAMBAR;?>" alt="Kost Makmur" width="100%" href="rumah-indekos/view?id=<?= $row->rumahindekos->ID_RUMAHINDEKOS ?>">
              <p> </p>
            </a>
          <div class= "col-lg-8">
          <h4 class="pull-right"><?php echo $row->rumahindekos->NAMA_RUMAHINDEKOS;?>
          </div>
            <!-- <div class= "col-lg-7 offset-md-1">
          <h5 class= "pull-right"> Rating: <?php echo Yii::$app->formatter->asDecimal($row->SUMS,2);?></h5></h4>
          </div> -->           
        </div>
        <?php
        }
        ?>
        </div>
      </div>
    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <div class="container text-center" style="margin-top:50px">
    <!-- <p>Please fill out the following fields to login:</p> -->
        <div class="row">
            <div class="col-md-20" style="padding-left:30%; padding-right:30%;">
            <h1><?= Html::encode($this->title) ?></h1>
                <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                    <!-- <img class="rounded-circle w-75 mx-auto d-block">
                            <?= Html::img('@web/image/Logo.jpeg',['alt'=>'some', 'class'=>'rounded-circle w-50 mx-auto d-block']);?> -->
                        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                        <?= $form->field($model, 'password')->passwordInput() ?>

                        <?= $form->field($model, 'rememberMe')->checkbox() ?>

                        <div style="color:#999;margin:1em 0">
                            Jika anda lupa kata sandi anda, anda dapat <?= Html::a('Mengatur ulang kata sandi', ['site/request-password-reset']) ?>.
                            <br>
                            Anda membutuhkan verifikasi email baru? <?= Html::a('Kirim ulang', ['site/resend-verification-email']) ?>
                        </div>

                        <div class="form-group">
                            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                        </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Mengatur ulang kata sandi';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Masukkan email anda. Sebuah link untuk mengatur ulang kata sandi akan dikirimkan.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'LKirim ulang email verifikasi';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Masukkan email anda. Email verifikasi akan dikirim ke email anda.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Mengatur ulang kata sandi';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Masukkan kata sandi baru:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use frontend\models\JenisKelamin;

$this->title = 'Registrasi Customer';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row">
        <div class="" style="padding-left:20%; padding-right:20%;" >
            <h1><?= Html::encode($this->title) ?></h1>

            <p>Isilah formulir dibawah ini untuk mendaftar sebagai Customer:</p>

            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($modelRegister, 'NAMA_CUSTOMER') ?>

                <?= $form->field($modelRegister, 'ALAMAT_CUSTOMER') ?>

                <?= $form->field($modelRegister, 'NO_TELEPON_CUSTOMER') ?>

                <?= $form->field($modelRegister, 'JENIS_KELAMIN')->label('Jenis Kelamin')->dropDownList(
                    ArrayHelper::map(JenisKelamin::find()->all(),'id','jenisKelamin'),
                    ['prompt'=>'Pilih Jenis Kelamin']
                    )
                ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => false]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'repassword')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signupVendor.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Registrasi Vendor';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row">
        <div class="" style="padding-left:20%; padding-right:20%;" >
        <h1><?= Html::encode($this->title) ?></h1>

        <p>Isilah formulir dibawah ini untuk mendaftar sebagai Vendor:</p>
    
        <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($modelRegisterVendor, 'NAMA_VENDOR') ?>

                <?= $form->field($modelRegisterVendor, 'ALAMAT_VENDOR') ?>

                <?= $form->field($modelRegisterVendor, 'NO_TELEPON__VENDOR') ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => false]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'repassword') ->passwordInput()?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>